apiVersion: wildfly.org/v1alpha1
kind: WildFlyServer
metadata:
  name: eap8
spec:
  applicationImage: eap8:latest
  replicas: 2
# use "eap8:latest" if you want to use the image built by helm
# else, use the Containerfile to build the image and reference that image here.
# for example: quay.io/balki404/eap8-app-ocp:1.0
